// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX7HJvbhn8f10ECBPQ-VLnUsvKzIF-eVo',
    appId: '1:833708739070:web:477fb28ba558a5f8d858af',
    messagingSenderId: '833708739070',
    projectId: 'arsneakers-console',
    authDomain: 'arsneakers-console.firebaseapp.com',
    storageBucket: 'arsneakers-console.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV7ZnnwbXRFX6Jg3Z7Dr8JiCoFGW-Z4to',
    appId: '1:833708739070:android:6a4273fccbb87c93d858af',
    messagingSenderId: '833708739070',
    projectId: 'arsneakers-console',
    storageBucket: 'arsneakers-console.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhQYE_AVbT1_uHWCpB56EsjvJjPGFLQJg',
    appId: '1:833708739070:ios:ef2b943c26729f22d858af',
    messagingSenderId: '833708739070',
    projectId: 'arsneakers-console',
    storageBucket: 'arsneakers-console.firebasestorage.app',
    iosBundleId: 'com.example.arsneakers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhQYE_AVbT1_uHWCpB56EsjvJjPGFLQJg',
    appId: '1:833708739070:ios:ef2b943c26729f22d858af',
    messagingSenderId: '833708739070',
    projectId: 'arsneakers-console',
    storageBucket: 'arsneakers-console.firebasestorage.app',
    iosBundleId: 'com.example.arsneakers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX7HJvbhn8f10ECBPQ-VLnUsvKzIF-eVo',
    appId: '1:833708739070:web:086b47aa94eae7ced858af',
    messagingSenderId: '833708739070',
    projectId: 'arsneakers-console',
    authDomain: 'arsneakers-console.firebaseapp.com',
    storageBucket: 'arsneakers-console.firebasestorage.app',
  );

}